resources:
- name: source-code-from-github
  type: git
  source:
    uri: git@github.com:jeyanagarjun/jarfile.git
    branch: main

- name: pcf-resource
  type: cf
  source:
    api: https://api.cf.us10-001.hana.ondemand.com/
    username: jeyanagarjun@gmail.com
    password: p@ssW0rds
    organization: 134aaaf4trial
    space: dev
    skip_cert_check: true
    
jobs:
- name: test-and-build
  public: true
  plan:
    - get: source-code-from-github
      trigger: true
    - task: run-test-and-build-jar-file
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: java
            tag: 8
        inputs:
        - name: source-code-from-github
        outputs:
        - name: jar-file
        caches:
        - path: source-code-from-github/.m2
        run:
          path: ./test-and-build.sh
    - put: pcf-resource
      params:
        file: jar-file/*.jar


